### PR TITLE
Fix CRLF issues.

### PR DESCRIPTION
**Pull request by sorenstoutner**
I am taking over maintenance of the Debian Courier package (which is currently not in very good shape).  In working to update it to 1.3.13, I noticed that three files have a large number of CRLF (Carriage-Return, Line-Feed) line endings, which is the Microsoft Windows standard.

imap/pop3testsuite.txt
imap/smaptestsuite.txt
imap/testsuite.txt

The typical Debian packaging workflow involves checking the upstream files into a Git repository and then later comparing them to a copy of the upstream tarball.  The Git repository automatically replaces the CRLF line endings with LF, which is the standard on Linux.  This causes the comparison phase of the package building to fail.

I can manually work around this issue in the packaging, but it would be easiest if the line endings in these files were all replaced with LF.  This patch does so, using copies of the files from the 1.3.13 tarball.

### CODE REVIEW

**Comment by svarshavchik** [comment]
As expected, make check failed.

These files themselves come from Courier's git repository. git should handle these files without any issues.

**Comment by sorenstoutner** [comment]
That is interesting.  Why do these checks fail if most of the lines in the files do not have CRLF line endings (some of the lines already have LF line endings)?  Is CRLF some part of the IMAP standard?

**Comment by svarshavchik** [comment]
Your hunch is correct. CRLF-terminated lines is not just a part of the IMAP standard, but also POP3, SMTP, and even HTTP.

As far as why not all lines have CRLF terminators is because the test suite includes other things than literal IMAP and POP3 output.

**Comment by sorenstoutner** [comment]
In that case I will make some custom adjustments to the Debian packaging workflow.  Specifically, I will need to enforce `autocrlf=false` across all contributors to the project, as well as on the server.

However, that shouldn't be too difficult to implement and I am happy to do so given that these files need CRLF for technical reasons.

**Pull request closed without merging**
